services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root12345678
    expose:
      - "3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    restart: always
